name: "Integration Github Mattermost"
description: "Send message to your Mattermost instance"
author: Singnet
inputs:
  webhook-url:
    description: "The URL of the Mattermost webhook"
    required: true
  message:
    description: "The message to send to Mattermost"
    required: true
  channel:
    description: "The channel on Mattermost to post the message (optional)"
    required: false
  username:
    description: "The username for posting on Mattermost (optional)"
    required: false
  icon:
    description: "The icon for the post on Mattermost (optional)"
    required: false
branding:
  icon: "bell"
  color: "red"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MATTERMOST_WEBHOOK_URL: ${{ inputs.webhook-url }}
    MATTERMOST_MESSAGE: ${{ inputs.message }}
    MATTERMOST_CHANNEL: ${{ inputs.channel }}
    MATTERMOST_USERNAME: ${{ inputs.username }}
    MATTERMOST_ICON: ${{ inputs.icon }}
